# Generated by Django 4.0 on 2023-07-13 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_users_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_active',
        ),
    ]
